{ config, lib, pkgs, swww, ... }:

with lib;
{
  options.modules.hyprland = {
    enable = mkOption { type = types.bool; default = false; };
  };

  config = mkIf config.modules.hyprland.enable {
    home.packages = with pkgs; [
      hyprland
      (swww.packages.${pkgs.system}.swww)
      grimblast
      wl-clipboard
      (nerdfonts.override { fonts = [ "FantasqueSansMono" ]; })
    ];

    wayland.windowManager.hyprland = {
      enable = true;
      package = pkgs.hyprland;
      xwayland.enable = true;
      settings = {
        "$mod" = "SUPER";
        autogenerated = 0;

        exec-once = [
          "swww-daemon"
          "swww img /etc/nixos/wallpaper"
        ];

        input = {
          repeat_delay = 400;
          repeat_rate  = 50;
          accel_profile = "flat";
          sensitivity = 0.3;
        };

        monitor = [
          "DP-3,3840x2160@120,0x0,1.0"
        ];

        general = {
          border_size = 1;
          no_border_on_floating = true;
          gaps_in = 0;
          gaps_out = -1;
          gaps_workspaces = 0;
          layout = "master";
          resize_on_border = true;
          extend_border_grab_area = true;
          hover_icon_on_border = true;
          allow_tearing = true;
          resize_corner = 0;
        };

        animations = {
          enabled = false;
        };

        master = {
          mfact = 0.5;
        };

        bind = [
          "$mod, Q, killactive,"
          "$mod, F, togglefloating,"
          "$mod, SPACE, exec, rofi -show run"
          "$mod SHIFT, S, exec, grimblast copy area --wait 2"

          "$mod, Return, exec, kitty"
          "$mod, W, exec, firefox"

          "$mod, mouse:272, movewindow,"
          #"$mod, mouse:273, resizewindow,"

          "$mod, Z, fullscreen, 0"
          "$mod, H, movefocus, l"
          "$mod, L, movefocus, r"
          "$mod, K, movefocus, u"
          "$mod, J, movefocus, d"
          "$mod SHIFT, H, movewindow, l"
          "$mod SHIFT, L, movewindow, r"
          "$mod SHIFT, K, movewindow, u"
          "$mod SHIFT, J, movewindow, d"

          "$mod, LEFT, resizeactive, -20 0"
          "$mod, RIGHT, resizeactive, 20 0"
          "$mod, UP, resizeactive, 0 -20"
          "$mod, DOWN, resizeactive, 0 20"
          "$mod, SHIFT LEFT, moveactive, -20 0"
          "$mod, SHIFT RIGHT, moveactive, 20 0"
          "$mod, SHIFT UP, moveactive, 0 -20"
          "$mod, SHIFT DOWN, moveactive, 0 20"

          "$mod, 1, workspace, 1"
          "$mod, 2, workspace, 2"
          "$mod, 3, workspace, 3"
          "$mod, 4, workspace, 4"
          "$mod, 5, workspace, 5"
          "$mod, 6, workspace, 6"
          "$mod, 7, workspace, 7"
          "$mod, 8, workspace, 8"
          "$mod, 9, workspace, 9"

          "$mod SHIFT, 1, movetoworkspace, 1"
          "$mod SHIFT, 2, movetoworkspace, 2"
          "$mod SHIFT, 3, movetoworkspace, 3"
          "$mod SHIFT, 4, movetoworkspace, 4"
          "$mod SHIFT, 5, movetoworkspace, 5"
          "$mod SHIFT, 6, movetoworkspace, 6"
          "$mod SHIFT, 7, movetoworkspace, 7"
          "$mod SHIFT, 8, movetoworkspace, 8"
          "$mod SHIFT, 9, movetoworkspace, 9"
        ];
      };
    };
  };
}
